import React, {useEffect,useMemo,useState} from 'react';
import {View,Text,ScrollView,Pressable,TextInput,StyleSheet,useWindowDimensions,ActivityIndicator,StatusBar} from 'react-native';
import {StatusBar as ExpoStatusBar} from 'expo-status-bar';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {SvgXml} from 'react-native-svg';
import {House,CalendarDays,HeartPulse,Wallet,ShoppingBasket,ListTodo,Target,Sparkles,Settings2,Plus,Check,ChevronRight,Clock3,Moon,Search,ScanLine,TrendingDown,LayoutGrid,Columns3,List,Bell,X,type LucideIcon} from 'lucide-react-native';
import {hero,fiscal} from './src/assets';
type Page='Início'|'Tarefas'|'Agenda'|'Saúde'|'Finanças'|'Compras'|'Metas'|'Insights'|'Configurações';
type Task={id:number;title:string;status:'A fazer'|'Em andamento'|'Concluído';area:string};
type Buy={id:number;name:string;brand:string;price:number;done:boolean};
const C={navy:'#17334F',muted:'#778B9E',blue:'#347FC8',aqua:'#47BBAE',line:'#DFEAF2',soft:'#F1F7FB',bg:'#F9FBFD'};
const nav:{name:Page;icon:LucideIcon}[]=[{name:'Início',icon:House},{name:'Tarefas',icon:ListTodo},{name:'Agenda',icon:CalendarDays},{name:'Saúde',icon:HeartPulse},{name:'Finanças',icon:Wallet},{name:'Compras',icon:ShoppingBasket},{name:'Metas',icon:Target},{name:'Insights',icon:Sparkles},{name:'Configurações',icon:Settings2}];
const initialTasks:Task[]=[{id:1,title:'Revisar apresentação',status:'A fazer',area:'Trabalho'},{id:2,title:'Estudar inglês',status:'Em andamento',area:'Pessoal'},{id:3,title:'Organizar orçamento',status:'A fazer',area:'Finanças'},{id:4,title:'Treino de força',status:'Concluído',area:'Saúde'},{id:5,title:'Planejar a semana',status:'A fazer',area:'Pessoal'}];
const initialBuys:Buy[]=[{id:1,name:'Leite integral 1L',brand:'Piracanjuba',price:5.49,done:false},{id:2,name:'Arroz 5kg',brand:'Tio João',price:27.9,done:false},{id:3,name:'Café 500g',brand:'Melitta',price:24.9,done:false},{id:4,name:'Ovos 12 unidades',brand:'Granja',price:12.5,done:true}];
const cash=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
function T({children,size=14,color=C.navy,bold=false,light=false,style}:any){return <Text style={[{color,fontSize:size,fontWeight:light?'300':bold?'600':'400',lineHeight:size*1.5},style]}>{children}</Text>}
function I({as:Icon,size=18,color=C.muted}: {as:LucideIcon;size?:number;color?:string}){return <Icon size={size} strokeWidth={1.7} color={color}/>}
function Btn({label,onPress,icon:Icon=Plus}: {label:string;onPress:()=>void;icon?:LucideIcon}){return <Pressable onPress={onPress} style={s.btn}><I as={Icon} size={16} color="#fff"/><T size={12} color="#fff" bold>{label}</T></Pressable>}
function Tab({name,onPress,on}: {name:string;onPress:()=>void;on:boolean}){return <Pressable onPress={onPress} style={[s.tab,on&&s.tabOn]}><T size={12} color={on?C.blue:C.muted} bold={on}>{name}</T></Pressable>}
function Heading({title,desc}: {title:string;desc?:string}){return <View style={{marginBottom:24}}><T size={38} light>{title}</T>{desc&&<T size={13} color={C.muted}>{desc}</T>}</View>}
function Bar({value}: {value:number}){return <View style={{height:6,backgroundColor:'#DCEAF3',borderRadius:9,overflow:'hidden'}}><View style={{width:String(value)+'%',height:6,backgroundColor:C.aqua}}/></View>}
function Graph({values=[18,39,28,57,35,61,49,72,52,80]}: {values?:number[]}){return <View style={{height:58,flexDirection:'row',gap:6,alignItems:'flex-end',marginTop:10}}>{values.map((v,i)=><View key={i} style={{flex:1,height:String(v)+'%',backgroundColor:C.blue,opacity:.25+i*.065,borderRadius:5}}/>)}</View>}
export default function App(){
 const desktop=useWindowDimensions().width>=850;
 const [page,setPage]=useState<Page>('Início'),[tasks,setTasks]=useState<Task[]>(initialTasks),[buys,setBuys]=useState<Buy[]>(initialBuys);
 const [loaded,setLoaded]=useState(false),[mode,setMode]=useState('Lista'),[draft,setDraft]=useState(''),[input,setInput]=useState(false),[scan,setScan]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let live=true;Promise.all([AsyncStorage.getItem('air:v1:tasks'),AsyncStorage.getItem('air:v1:buys')]).then(([a,b])=>{if(!live)return;if(a){try{setTasks(JSON.parse(a))}catch{}}if(b){try{setBuys(JSON.parse(b))}catch{}}setLoaded(true)}).catch(()=>setLoaded(true));return()=>{live=false}},[]);
 useEffect(()=>{if(loaded)AsyncStorage.setItem('air:v1:tasks',JSON.stringify(tasks)).catch(()=>{})},[loaded,tasks]);
 useEffect(()=>{if(loaded)AsyncStorage.setItem('air:v1:buys',JSON.stringify(buys)).catch(()=>{})},[loaded,buys]);
 const open=tasks.filter(t=>t.status!=='Concluído').length;
 const next=(id:number)=>setTasks(x=>x.map(t=>t.id===id?{...t,status:t.status==='A fazer'?'Em andamento':t.status==='Em andamento'?'Concluído':'A fazer'}:t));
 const add=()=>{if(!draft.trim())return;setTasks(x=>[{id:Date.now(),title:draft.trim(),status:'A fazer',area:'Pessoal'},...x]);setDraft('');setInput(false)};
 const go=(p:Page)=>{setPage(p);setNotice('')};
 const link=(n:{name:Page;icon:LucideIcon},compact=false)=><Pressable key={n.name} onPress={()=>go(n.name)} style={[compact?s.mobileLink:s.link,page===n.name&&{backgroundColor:'#DFEFFD'}]}><I as={n.icon} color={page===n.name?C.blue:C.muted} size={compact?20:18}/><T size={compact?10:13} color={page===n.name?C.blue:C.muted} bold={page===n.name}>{n.name}</T></Pressable>;
 const agenda=[['09:00','Revisão do projeto'],['14:00','Almoço com a equipe'],['19:00','Academia']];
 const home=<View style={{gap:23}}><View style={s.hero}><SvgXml xml={hero} width="100%" height="100%" preserveAspectRatio="xMidYMid slice"/><View style={s.heroText}><T size={11} color={C.muted}>SEU DIA EM PERSPECTIVA</T><T size={desktop?43:34} light>Bom dia, Ana.</T><T color={C.muted} size={12}>Mais clareza para uma vida extraordinária.</T></View></View><View style={[s.flex,desktop&&{flexDirection:'row'}]}><Pressable onPress={()=>go('Agenda')} style={[s.card,{flex:1.2}]}><T bold>Agenda de hoje</T>{agenda.map(([h,n])=><View key={h} style={s.row}><T color={C.blue} size={12}>{h}</T><T size={12}>{n}</T></View>)}</Pressable><View style={[s.flex,{flex:1},desktop&&{flexDirection:'row'}]}><Pressable onPress={()=>go('Tarefas')} style={[s.card,{flex:1}]}><T size={12} bold>Próximas 3 horas</T><T size={28} light>{open} tarefas</T><T size={11} color={C.muted}>Reveja suas prioridades</T></Pressable><Pressable onPress={()=>go('Finanças')} style={[s.card,{flex:1}]}><T size={12} bold>Gastos últimas 24h</T><T size={27} light>{cash(181.3)}</T><Graph/></Pressable></View></View><View style={[s.flex,desktop&&{flexDirection:'row'}]}><Pressable onPress={()=>go('Saúde')} style={{flex:1,padding:14}}><T size={20}>Bem-estar</T><T size={30} light>7h 32min</T><T color={C.aqua} size={12}>Sono bom</T><Graph/></Pressable><Pressable onPress={()=>go('Metas')} style={{flex:1,padding:14}}><T size={20}>Metas da semana</T><T size={30} light>3 de 5</T><T color={C.muted} size={12}>Objetivos em andamento</T><Bar value={60}/></Pressable></View><Pressable onPress={()=>go('Insights')} style={s.glass}><I as={Sparkles} color={C.blue} size={23}/><View style={{flex:1}}><T bold>Insight do AIR</T><T size={12} color={C.muted}>Progresso consistente esta semana. Mantenha suas prioridades e reserve tempo para descansar.</T></View><I as={ChevronRight}/></Pressable></View>;
 const tasksPage=<View><View style={s.head}><Heading title="Tarefas" desc="Organize hoje, evolua amanhã."/>{<Btn label="Nova tarefa" onPress={()=>setInput(true)}/>}</View><View style={s.row}>{['Lista','Kanban','Grade'].map(t=><Tab key={t} name={t} on={mode===t} onPress={()=>setMode(t)}/>)}</View>{input&&<View style={s.row}><TextInput style={s.input} value={draft} onChangeText={setDraft} placeholder="Digite sua tarefa" onSubmitEditing={add}/><Btn label="Adicionar" onPress={add}/><Pressable onPress={()=>setInput(false)}><I as={X}/></Pressable></View>}{mode==='Lista'?tasks.map(t=><Pressable key={t.id} onPress={()=>next(t.id)} style={s.item}><View style={[s.check,t.status==='Concluído'&&{backgroundColor:C.aqua}]}>{t.status==='Concluído'&&<I as={Check} size={13} color="#fff"/>}</View><View style={{flex:1}}><T bold>{t.title}</T><T size={11} color={C.muted}>{t.area} · {t.status}</T></View><I as={ChevronRight}/></Pressable>):mode==='Kanban'?<ScrollView horizontal><View style={s.row}>{(['A fazer','Em andamento','Concluído'] as const).map(st=><View key={st} style={s.kanban}><T bold>{st} · {tasks.filter(t=>t.status===st).length}</T>{tasks.filter(t=>t.status===st).map(t=><Pressable onPress={()=>next(t.id)} key={t.id} style={s.kanbanCard}><T>{t.title}</T><T size={11} color={C.muted}>{t.area}</T></Pressable>)}</View>)}</View></ScrollView>:<View style={s.tiles}>{tasks.map(t=><Pressable onPress={()=>next(t.id)} key={t.id} style={s.tile}><I as={LayoutGrid} color={C.blue}/><T bold>{t.title}</T><T size={11} color={C.muted}>{t.status}</T></Pressable>)}</View>}<T size={11} color={C.muted}>Toque na tarefa para avançar o status. Salvo automaticamente no dispositivo.</T></View>;
 const otherScreens:Record<Exclude<Page,'Início'|'Tarefas'>,React.ReactNode>={
 'Agenda':<View><Heading title="Agenda" desc="Seu tempo, no seu ritmo."/><T size={23} light>Compromissos de hoje</T>{agenda.map(([h,n])=><View key={h} style={s.item}><I as={CalendarDays} color={C.blue}/><T color={C.blue}>{h}</T><T>{n}</T></View>)}</View>,
 'Saúde':<View><Heading title="Saúde" desc="Sua rotina de bem-estar, com clareza."/><View style={s.glass}><I as={Moon} color={C.blue} size={28}/><View><T color={C.muted}>Sono da última noite</T><T size={35} light>7h 32min</T><T color={C.aqua}>Boa qualidade</T></View></View>{[['Passos',86],['Atividade física',58],['Hidratação',75]].map(([name,val])=><View key={String(name)} style={{paddingVertical:14,gap:9}}><T>{name} · {val}%</T><Bar value={Number(val)}/></View>)}<T size={11} color={C.muted}>Dados ilustrativos. Integração Mi Fitness/Apple Saúde/Health Connect ainda não disponível.</T></View>,
 'Finanças':<View><Heading title="Finanças" desc="Entenda para onde seu dinheiro vai."/>{<View style={s.glass}><I as={Wallet} color={C.blue}/><View style={{flex:1}}><T color={C.muted}>Gastos demonstrativos este mês</T><T size={38} light>{cash(2848.9)}</T><T size={12} color={C.aqua}>12% abaixo da média anterior</T><Graph/></View></View>}{[['Mercado',148.9],['Transporte',32.4],['Farmácia',64.32],['Assinaturas',39.9]].map(([name,v])=><View key={String(name)} style={s.item}><I as={Wallet} color={C.blue}/><View style={{flex:1}}><T>{name}</T><T size={11} color={C.muted}>Despesa de exemplo</T></View><T bold>-{cash(Number(v))}</T></View>)}<T size={11} color={C.muted}>Open Finance será somente leitura de gastos autorizados. Nenhum banco conectado.</T></View>,
 'Compras':<View><View style={s.head}><Heading title="Compras" desc="Sua lista inteligente."/><Btn label="Ler NFC-e" icon={ScanLine} onPress={()=>setScan(!scan)}/></View><View style={s.glass}><I as={ShoppingBasket} size={25} color={C.blue}/><View><T color={C.muted}>Itens pendentes</T><T size={28} light>{buys.filter(p=>!p.done).length}</T><T size={12}>{cash(buys.filter(p=>!p.done).reduce((a,b)=>a+b.price,0))}</T></View></View>{buys.map(b=><Pressable key={b.id} style={s.item} onPress={()=>setBuys(x=>x.map(v=>v.id===b.id?{...v,done:!v.done}:v))}><View style={[s.check,b.done&&{backgroundColor:C.aqua}]}>{b.done&&<I as={Check} color="#fff" size={12}/>}</View><View style={{flex:1}}><T bold>{b.name}</T><T size={11} color={C.muted}>{b.brand}</T></View><T>{cash(b.price)}</T></Pressable>)}<Btn label="Adicionar item de exemplo" onPress={()=>setBuys(v=>[{id:Date.now(),name:'Banana 1kg',brand:'Hortifruti',price:5.99,done:false},...v])}/>{scan&&<View style={{marginTop:20,alignItems:'center',gap:12}}><SvgXml xml={fiscal} width={210} height={210}/><T>Leitura fiscal real ainda não integrada.</T><Btn label="Fechar" onPress={()=>setScan(false)} icon={X}/></View>}<T size={11} color={C.muted}>Preços são fictícios. Histórico real dependerá da consulta fiscal autorizada.</T></View>,
 'Metas':<View><Heading title="Metas e hábitos" desc="Resultados que começam com pequenas ações."/>{[['Estudar 12 horas',75],['Exercícios semanais',60],['Economizar no mercado',45],['Leitura',80]].map(([k,v])=><View key={String(k)} style={{marginBottom:25,gap:9}}><T bold>{k}</T><T size={12} color={C.muted}>{v}% da meta</T><Bar value={Number(v)}/></View>)}</View>,
 'Insights':<View><Heading title="AIR Insights" desc="Inteligência para decisões melhores."/><View style={[s.glass,{alignItems:'flex-start'}]}><I as={Sparkles} color={C.blue} size={25}/><View style={{flex:1}}><T size={26} light>Uma semana em equilíbrio.</T><T color={C.muted}>Tarefas concluídas, sono adequado e gastos controlados formam seu panorama desta demonstração.</T><Graph/></View></View>{['Organize blocos de foco pela manhã','Mantenha intervalos de descanso','Revise seu orçamento semanal'].map(t=><View key={t} style={s.item}><I as={Sparkles} color={C.blue}/><T>{t}</T></View>)}<T size={11} color={C.muted}>Estes insights são exemplos, não análise de dados pessoais reais.</T></View>,
 'Configurações':<View><Heading title="Configurações" desc="Suas escolhas, seus dados."/><T size={17} bold>Privacidade e integrações</T>{['Open Finance (somente leitura) — pendente','Mi Fitness / Apple Saúde — pendente','Google e Outlook Calendar — pendente','Leitura de NFC-e — pendente'].map(t=><View key={t} style={s.item}><I as={Settings2} color={C.blue}/><T>{t}</T></View>)}</View>
 };
 return <View style={s.root}><ExpoStatusBar style="dark"/><StatusBar barStyle="dark-content"/><View style={{flex:1,flexDirection:'row'}}>
 {desktop&&<View style={s.sidebar}><Pressable onPress={()=>go('Início')} style={{marginBottom:34}}><T size={57} light style={{letterSpacing:-7}}>air.</T><T size={10} color={C.muted}>PERSONAL OS</T></Pressable>{nav.map(x=>link(x))}<View style={{flex:1}}/><T size={11} color={C.muted}>Modo demonstração</T></View>}
 <View style={{flex:1}}><View style={s.top}><Pressable onPress={()=>go('Início')}><T size={desktop?13:38} light style={!desktop?{letterSpacing:-4}:undefined}>{desktop?'AIR · Personal OS':'air.'}</T></Pressable><View style={{flex:1}}/><T size={10} color={C.muted}>DEMONSTRAÇÃO</T><I as={Bell}/></View>
 <ScrollView key={page} contentContainerStyle={{paddingHorizontal:desktop?44:19,paddingTop:14,paddingBottom:130}} keyboardShouldPersistTaps="handled"><View style={{width:'100%',maxWidth:1200,alignSelf:'center'}}>{!loaded?<ActivityIndicator/>:page==='Início'?home:page==='Tarefas'?tasksPage:otherScreens[page]}{notice!==''&&<T>{notice}</T>}</View></ScrollView>
 {!desktop&&<View style={s.bottom}>{nav.filter(x=>['Início','Tarefas','Agenda','Finanças','Configurações'].includes(x.name)).map(x=>link(x,true))}</View>}
 </View></View></View>;
}
const s=StyleSheet.create({
 root:{flex:1,backgroundColor:C.bg},sidebar:{width:218,backgroundColor:'#F0F7FC',borderRightWidth:1,borderColor:C.line,padding:18,paddingTop:28},
 link:{padding:13,borderRadius:14,flexDirection:'row',alignItems:'center',gap:12,marginBottom:3},
 mobileLink:{alignItems:'center',justifyContent:'center',gap:4,padding:7,minWidth:52},
 top:{height:76,flexDirection:'row',alignItems:'center',gap:16,paddingHorizontal:26},
 bottom:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'#F6FAFE',borderTopWidth:1,borderColor:C.line,flexDirection:'row',justifyContent:'space-around',paddingVertical:8},
 hero:{height:222,borderRadius:24,overflow:'hidden',backgroundColor:'#DFEEF8'},
 heroText:{position:'absolute',top:30,left:24,right:20,gap:4},
 flex:{gap:16},
 row:{flexDirection:'row',alignItems:'center',gap:12,marginTop:11},
 card:{backgroundColor:'#fff',borderWidth:1,borderColor:C.line,borderRadius:19,padding:19,gap:10},
 glass:{backgroundColor:'#EAF5FC',borderWidth:1,borderColor:'#fff',borderRadius:22,padding:22,flexDirection:'row',alignItems:'center',gap:16},
 head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},
 item:{borderBottomWidth:1,borderColor:C.line,paddingVertical:18,flexDirection:'row',alignItems:'center',gap:13},
 check:{width:21,height:21,borderWidth:1,borderColor:'#AFC6D7',borderRadius:11,alignItems:'center',justifyContent:'center'},
 btn:{backgroundColor:C.blue,borderRadius:12,paddingVertical:11,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:7},
 tab:{padding:10,paddingHorizontal:17,backgroundColor:'#EDF3F8',borderRadius:12},tabOn:{backgroundColor:'#DCEEFE'},
 input:{backgroundColor:'#fff',borderWidth:1,borderColor:C.line,borderRadius:11,padding:12,flex:1,minWidth:70},
 kanban:{width:228,backgroundColor:'#EDF5FB',padding:13,borderRadius:14,gap:12,marginBottom:20,minHeight:260},
 kanbanCard:{backgroundColor:'#fff',padding:13,borderRadius:11,gap:6},
 tiles:{flexDirection:'row',flexWrap:'wrap',gap:14,marginBottom:22},
 tile:{width:'47%',minHeight:130,backgroundColor:'#fff',borderWidth:1,borderColor:C.line,padding:15,borderRadius:16,gap:9}
});
